### ISSUE TITLE
Upgrade to Vert.x 3.5.1

### ISSUE THREAD

**Issue by leogomes** [flamegrapher/flamegrapher#12]
It should fix the annoying Netty warning linked to modules in JDK 9+

**Comment by leogomes** [comment]
Need to wait for a new release. 3.5.1 still doesn't fix it.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vertx/_bJhlRarzRs/bfh5TSXRAgAJ

**Comment by nbogojevic** [comment]
Done in #31 (to version 3.5.2)
