### ISSUE TITLE
jcmd options have changed in JDK10

### ISSUE THREAD

**Issue by nbogojevic** [flamegrapher/flamegrapher#6]
recording option is no longer available in jdk 10, we should use name option. This option can be given on JFR.start, check, stop and dump.

Also as jdk 9 is EOL, should switch everything to 10.

**Comment by leogomes** [comment]
This is being taken into account here: https://github.com/flamegrapher/flamegrapher/pull/5/files#diff-1c491bff7236b9689bbdee85f470f384R143

But should be changed to "jdk > 8" :)

**Comment by leogomes** [comment]
Should be fixed with https://github.com/flamegrapher/flamegrapher/pull/5

**Comment by leogomes** [comment]
Closing it. @nbogojevic feel free to re-open if you find any issue on Windows.
